In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
import collections
import random

In [3]:
import utils

In [4]:
df_predictions = pd.read_csv(utils.latest_smart_prediction(), index_col=0)

/home/ubuntu/.local/lib/python3.6/site-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [5]:
df_predictions.head()

,true_change,optimal_change,optimal_change_with_fee,address_type,power_of_ten_2,power_of_ten_3,power_of_ten_4,power_of_ten_5,power_of_ten_6,power_of_ten_7,...,fp_version,fp_locktime,fp_rbf,fp_segwit,fp_possible_segwit,fp_ordered_inouts,fp_address_type,fp_p2sh,fp_p2wsh,fp_p2wpkh
36485,0,-1,-1,1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,1,-1,-1,-1
38619,0,0,0,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,0,-1,-1,-1
44447,1,1,1,-1,-1,-1,-1,-1,-1,0,...,-1,-1,-1,-1,-1,-1,1,-1,-1,-1
46689,0,0,0,1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
47882,1,1,1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [6]:
outcome = df_predictions['true_change']

In [7]:
df_predictions = df_predictions.drop(columns="true_change")

In [8]:
df_predictions = df_predictions.drop(columns="pow10")

In [9]:
df_predictions = df_predictions.drop(columns="two_hops")

In [10]:
df_predictions.head()

,optimal_change,optimal_change_with_fee,address_type,power_of_ten_2,power_of_ten_3,power_of_ten_4,power_of_ten_5,power_of_ten_6,power_of_ten_7,fp_inout_count,...,fp_version,fp_locktime,fp_rbf,fp_segwit,fp_possible_segwit,fp_ordered_inouts,fp_address_type,fp_p2sh,fp_p2wsh,fp_p2wpkh
36485,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,1,-1,-1,-1
38619,0,0,-1,-1,-1,-1,-1,-1,-1,0,...,-1,-1,-1,-1,-1,-1,0,-1,-1,-1
44447,1,1,-1,-1,-1,-1,-1,-1,0,1,...,-1,-1,-1,-1,-1,-1,1,-1,-1,-1
46689,0,0,1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
47882,1,1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [11]:
values = []
for col in df_predictions.columns:
    column = df_predictions[col]
    correct = column.eq(outcome).sum()
    incorrect = column.ne(outcome).sum() - column.eq(-1).sum()
    tpr = round(correct / len(column), 6)
    fpr = round(incorrect / len(column), 6)
    print(tpr, "&", fpr, col)
    values.append((fpr, tpr))

0.305982 & 0.026317 optimal_change
0.2391 & 0.020221 optimal_change_with_fee
0.236927 & 0.030544 address_type
0.467048 & 0.011745 power_of_ten_2
0.419994 & 0.006165 power_of_ten_3
0.374834 & 0.005068 power_of_ten_4
0.302347 & 0.00557 power_of_ten_5
0.211132 & 0.004961 power_of_ten_6
0.106845 & 0.000501 power_of_ten_7
0.263076 & 0.107035 fp_inout_count
0.283425 & 0.12945 fp_output_count
0.100237 & 0.06131 fp_zeroconf
0.139837 & 0.000551 fp_multisig
0.239226 & 0.01352 fp_p2pkh
0.117414 & 0.025319 fp_absolute_fee
0.041868 & 0.008099 fp_relative_fee
0.245298 & 0.003765 fp_version
0.306533 & 0.002925 fp_locktime
0.075313 & 0.002698 fp_rbf
0.190708 & 0.020918 fp_segwit
0.02142 & 0.000763 fp_possible_segwit
0.261993 & 0.052919 fp_ordered_inouts
0.294188 & 0.022907 fp_address_type
0.268645 & 0.015247 fp_p2sh
0.06311 & 0.007178 fp_p2wsh
0.180882 & 0.019025 fp_p2wpkh